apiVersion: v1
kind: Secret
metadata:
  name: bucketrepo-config
  namespace: {{ .Release.Namespace }}
  annotations:
    config/checksum: {{ print .Values.config | sha256sum }}
type: Opaque
stringData:
  config.yaml: |
{{ include (print .Template.BasePath "/_config.yaml.tpl") . | indent 4 }}
