{{- if .Values.serviceaccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "jx.name" . }}
    chart: {{ template "jx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.serviceaccount.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
{{- end }}
