http:
    addr: ":8080"

storage:
    enabled: false
    bucket_url: "gs://bucketrepo"

charts:
    path: "charts"

cache:
    base_dir: "/tmp/bucketrepo"

repositories:
    - url: "https://repo1.maven.org/maven2"
    - url: "http://uk.maven.org/maven2/"
