http:
    addr: ":8080"

storage:
    enabled: true
    bucket_url: "s3://private-repository.cuebiq.com/releases/"
    prefix: "releases"

cache:
    base_dir: "/Users/apilo/bucketcb"

repository:
    url: "https://repo1.maven.org/maven2"
